<?php

declare(strict_types=1);

namespace yii2\extensions\phpstan\tests\support\stub;

/**
 * This is the model class for table "invoice".
 *
 * Stub ActiveRecord model as generated by Gii, with the non-generic {@see InvoiceQuery}, for query model inference
 * tests.
 *
 * @property int $id
 * @property string $number
 *
 * @property Comment[] $comments
 */
class Invoice extends \yii\db\ActiveRecord
{
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'number' => 'Number',
        ];
    }

    /**
     * @return InvoiceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new InvoiceQuery(static::class);
    }

    /**
     * Gets query for [[Comments]].
     *
     * @return CommentQuery|\yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::class, ['invoice_id' => 'id']);
    }

    public function rules()
    {
        return [
            [['number'], 'required'],
            [['number'], 'string', 'max' => 255],
        ];
    }

    public static function tableName()
    {
        return 'invoice';
    }
}
