<?php

declare(strict_types=1);

namespace yii2\extensions\phpstan\tests\support\stub;

/**
 * This is the ActiveQuery class for [[Invoice]].
 *
 * Stub non-generic ActiveQuery as generated by Gii, with a `paid()` scope returning `self`, for query model inference
 * tests.
 *
 * @see Invoice
 */
class InvoiceQuery extends \yii\db\ActiveQuery
{
    /**
     * @return Invoice[]|array
     */
    public function all($db = null)
    {
        return parent::all($db);
    }

    /**
     * @return Invoice|array|null
     */
    public function one($db = null)
    {
        return parent::one($db);
    }

    /*public function active()
    {
        return $this->andWhere('[[status]]=1');
    }*/

    public function paid(): self
    {
        return $this->andWhere(['paid' => 1]);
    }
}
