<?php

declare(strict_types=1);

use yii\caching\{ArrayCache, CacheInterface, DummyCache, FileCache};
use yii\di\Instance;
use yii\web\{Request, View};
use yii2\extensions\phpstan\tests\support\stub\{InvokableViewFactory, MyActiveRecord, PlainService};

return [
    'components' => [
        'arrayCallable' => [InvokableViewFactory::class, '__invoke'],
        'arrayClass' => [
            'class' => View::class,
            'title' => 'Home',
        ],
        'arrayClassAndDunderClass' => [
            'class' => Request::class,
            '__class' => View::class,
        ],
        'arrayClassLeadingBackslash' => ['class' => '\yii\web\View'],
        'arrayClassNamingAliasedId' => ['class' => CacheInterface::class],
        'arrayDunderClass' => [
            '__class' => View::class,
            'title' => 'Home',
        ],
        'arrayWithoutClass' => ['title' => 'Home'],
        'closureBuiltin' => static fn(): object => new View(),
        'closureClass' => static fn(): View => new View(),
        'closureIntersection' => static fn(): Countable&Traversable => new ArrayObject(),
        'closureNullable' => static fn(): View|null => random_int(0, 1) === 1 ? new View() : null,
        'closureReturningAliasedId' => static fn(): CacheInterface => new ArrayCache(),
        'closureUnion' => static fn(): View|Request => random_int(0, 1) === 1 ? new View() : new Request(),
        'closureUntyped' => static fn() => new View(),
        'containerAlias' => 'mailer.alias',
        'containerAliasUnresolvable' => 'closureUntyped',
        'containerArrayAliasUnresolvable' => [
            'class' => 'closureUntyped',
            'title' => 'Home',
        ],
        'containerCycle' => 'cycle.a',
        'instance' => Instance::of('view'),
        'invokableObject' => new InvokableViewFactory(),
        'null' => null,
        'object' => new View(),
        'objectOfAliasedId' => new ArrayCache(),
        'string' => View::class,
        'stringLeadingBackslash' => '\yii\web\View',
        'stringNamingAliasedId' => CacheInterface::class,
    ],
    'container' => [
        'definitions' => [
            'arrayCallable' => [InvokableViewFactory::class, '__invoke'],
            'arrayClass' => ['class' => SplStack::class],
            'arrayClassAndDunderClass' => [
                'class' => SplStack::class,
                '__class' => ArrayObject::class,
            ],
            'arrayClassLeadingBackslash' => ['class' => '\SplStack'],
            'arrayClassNamingAliasedId' => ['class' => CacheInterface::class],
            'arrayDunderClass' => ['__class' => SplStack::class],
            ArrayCache::class => DummyCache::class,
            ArrayObject::class => static fn() => new SplStack(),
            'arrayWithoutClass' => ['flag' => 'foo'],
            \yii\base\Configurable::class => ['flag' => 'foo'],
            \yii\caching\Cache::class => ['flag' => 'foo'],
            'app\missing\Service' => ['flag' => 'foo'],
            CacheInterface::class => FileCache::class,
            'closureBuiltin' => static fn(): object => new SplStack(),
            'closureClass' => static fn(): SplStack => new SplStack(),
            'closureIntersection' => static fn(): Countable&Traversable => new ArrayObject(),
            'closureNullable' => static fn(): SplStack|null => random_int(0, 1) === 1 ? new SplStack() : null,
            'closureReturningAliasedId' => static fn(): CacheInterface => new ArrayCache(),
            'closureUnion' => static fn(): SplStack|ArrayObject => random_int(0, 1) === 1
                ? new SplStack()
                : new ArrayObject(),
            'closureUntyped' => static fn() => new SplStack(),
            'closureReturningAliasedId.alias' => 'closureReturningAliasedId',
            'cycle.a' => 'cycle.b',
            'cycle.b' => 'cycle.a',
            'emptyDefinitionAlias' => SplObjectStorage::class,
            'instance' => Instance::of(SplStack::class),
            'instanceNamingAliasedId' => Instance::of('mailer.alias'),
            'instanceNamingUnresolvableId' => Instance::of('closureUntyped'),
            'invokableObject' => new InvokableViewFactory(),
            'mailer.alias' => 'mailer.real',
            'mailer.arrayAlias' => ['class' => 'mailer.real'],
            'mailer.chain' => 'mailer.alias',
            'mailer.real' => ['class' => View::class],
            'nestedList' => [['class' => SplStack::class]],
            MyActiveRecord::class => ['flag' => 'foo'],
            'null' => null,
            'object' => new SplStack(),
            'objectOfAliasedId' => new ArrayCache(),
            PlainService::class => ['mode' => 'sync'],
            'plainService.alias' => PlainService::class,
            'singletonClosureOverride' => FileCache::class,
            'singletonClosureOverride.alias' => 'singletonClosureOverride',
            'singletonEmptyOverride' => FileCache::class,
            'singletonInstanceOverride' => FileCache::class,
            'singletonOverride' => new ArrayCache(),
            'singletonResolvedOverride' => static fn() => new ArrayCache(),
            SplObjectStorage::class => [],
            'string' => SplStack::class,
            'stringLeadingBackslash' => '\SplStack',
            'stringNamingAliasedId' => CacheInterface::class,
            'unresolvable.alias' => 'closureUntyped',
            'unresolvable.arrayAlias' => ['class' => 'closureUntyped'],
            'unresolvable.chain' => 'unresolvable.alias',
            View::class => [],
            'wrappedArrayWithParams' => [
                ['class' => SplStack::class],
                [],
            ],
            'wrappedClosureReturningAliasedId' => [
                static fn(): CacheInterface => new ArrayCache(),
                [],
            ],
            'wrappedStringWithParams' => [SplStack::class, []],
        ],
        'singletons' => [
            'singletonAlias' => 'mailer.chain',
            'singletonClosureClass' => static fn(): SplStack => new SplStack(),
            'singletonClosureOverride' => static fn() => new ArrayCache(),
            'singletonClosureUntyped' => static fn() => new SplStack(),
            'singletonEmptyOverride' => [],
            'singletonInstance' => Instance::of(SplStack::class),
            'singletonInstanceOverride' => Instance::of(ArrayCache::class),
            'singletonOverride' => CacheInterface::class,
            'singletonResolvedOverride' => FileCache::class,
            'singletonString' => '\SplStack',
            'singletonWrappedArrayWithParams' => [
                ['__class' => SplStack::class],
                [],
            ],
        ],
    ],
];
