<?php

declare(strict_types=1);

namespace yii2\extensions\phpstan\type;

use PhpParser\Node\Expr\{StaticCall, Variable};
use PhpParser\Node\Name;
use PHPStan\Analyser\Scope;
use PHPStan\Reflection\{MethodReflection, ParametersAcceptorSelector};
use PHPStan\Type\{DynamicStaticMethodReturnTypeExtension, ObjectType, Type, TypeCombinator};
use PHPStan\Type\Generic\GenericObjectType;
use yii\db\{ActiveQuery, ActiveRecord};

use function count;
use function in_array;

/**
 * Binds the rows of the {@see ActiveQuery} returned by an {@see ActiveRecord} static method to the called model.
 *
 * A custom query class without generic PHPDoc, such as one generated by Gii, never binds the query's `T` to its
 * model, so `Post::find()->one()` would yield `array|Post|null` or `array<mixed>|ActiveRecord|null`. When the natively
 * resolved return type is a single {@see ActiveQuery} class whose `T` accepts the called model but is wider than it,
 * this extension returns that query type intersected with `ActiveQuery<Model>`. The result keeps every method and the
 * accepted type of the custom query class, while PHPStan intersects the return types of `one()`, `all()`, and the
 * fluent methods inherited from Yii, which yields `Post|null` and `array<Post>`.
 *
 * The model is the class named at the call site: a class name, `self`, `static`, `parent`, or `$this` (all resolved to
 * `static` of the calling class, as PHP forwards late static binding), or the object or `class-string` type of an
 * expression. Queries whose `T` is already the called model or narrower, such as `ActiveQuery<static>` or a generic
 * custom query class, are left unchanged.
 *
 * {@see ActiveQueryDynamicMethodReturnTypeExtension} for `asArray()`, `batch()`, and `each()` on the resulting type.
 * {@see DynamicStaticMethodReturnTypeExtension} for PHPStan dynamic static return type extension contract.
 */
final class ActiveRecordQueryDynamicStaticMethodReturnTypeExtension implements DynamicStaticMethodReturnTypeExtension
{
    /**
     * Returns the Yii Active Record class supported by this extension.
     *
     * @phpstan-return class-string
     */
    public function getClass(): string
    {
        return ActiveRecord::class;
    }

    /**
     * Resolves the query type returned by a static method call with its rows bound to the called model.
     *
     * @param MethodReflection $methodReflection Reflection of the called static method.
     * @param StaticCall $methodCall Static method call whose class expression names the model.
     * @param Scope $scope Current PHPStan analysis scope.
     *
     * @return Type|null Query type intersected with `ActiveQuery<Model>`, or `null` to keep PHPStan's answer when the
     * call is a first-class callable, the return type is not a single {@see ActiveQuery} class, the model cannot be
     * resolved, or the query's `T` does not strictly widen the model.
     */
    public function getTypeFromStaticMethodCall(
        MethodReflection $methodReflection,
        StaticCall $methodCall,
        Scope $scope,
    ): Type|null {
        if ($methodCall->isFirstClassCallable()) {
            return null;
        }

        $queryType = ParametersAcceptorSelector::selectFromArgs(
            $scope,
            $methodCall->getArgs(),
            $methodReflection->getVariants(),
        )->getReturnType();

        if (
            count($queryType->getObjectClassNames()) !== 1
            || (new ObjectType(ActiveQuery::class))->isSuperTypeOf($queryType)->yes() === false
        ) {
            return null;
        }

        $modelType = $this->resolveModelType($methodCall, $scope);

        if ($modelType === null || $modelType->isObject()->yes() === false) {
            return null;
        }

        $rowType = $queryType->getTemplateType(ActiveQuery::class, 'T');

        if ($modelType->isSuperTypeOf($rowType)->yes() || $rowType->isSuperTypeOf($modelType)->yes() === false) {
            return null;
        }

        return TypeCombinator::intersect($queryType, new GenericObjectType(ActiveQuery::class, [$modelType]));
    }

    /**
     * Returns whether a variant of the reflected static method may return an {@see ActiveQuery}.
     */
    public function isStaticMethodSupported(MethodReflection $methodReflection): bool
    {
        $activeQueryType = new ObjectType(ActiveQuery::class);

        foreach ($methodReflection->getVariants() as $variant) {
            if ($activeQueryType->isSuperTypeOf($variant->getReturnType())->no() === false) {
                return true;
            }
        }

        return false;
    }

    /**
     * Resolves the model type named by the class expression of the static call.
     *
     * @param StaticCall $methodCall Static method call to read the class expression from.
     * @param Scope $scope Current PHPStan analysis scope.
     *
     * @return Type|null `static` of the calling class for `self`, `static`, `parent`, and `$this`, the named class for
     * any other name, the object or `class-string` type of any other expression, or `null` for `self`, `static`,
     * `parent`, or `$this` outside a class.
     */
    private function resolveModelType(StaticCall $methodCall, Scope $scope): Type|null
    {
        $class = $methodCall->class;

        if ($class instanceof Name) {
            if (in_array($class->toLowerString(), ['self', 'static', 'parent'], true)) {
                return $scope->isInClass() ? $scope->resolveTypeByName(new Name('static')) : null;
            }

            return new ObjectType($scope->resolveName($class));
        }

        if ($class instanceof Variable && $class->name === 'this') {
            return $scope->isInClass() ? $scope->resolveTypeByName(new Name('static')) : null;
        }

        return $scope->getType($class)->getObjectTypeOrClassStringObjectType();
    }
}
