on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: build

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      composer-command: |
        composer require yiisoft/yii2:22.0.x-dev --prefer-dist --no-progress --no-interaction --no-scripts --ansi
      concurrency-group: phpunit-${{ github.workflow }}-${{ github.ref }}
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1', '8.2', '8.3', '8.4']
  phpunit-compatibility:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    concurrency:
      group: compatibility-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    with:
      concurrency-group: compatibility-${{ github.workflow }}-${{ github.ref }}
      extensions: intl
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1', '8.2', '8.3', '8.4']
