on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'

name: compatibility

jobs:
  phpunit:
    uses: php-forge/actions/.github/workflows/phpunit.yml@main
    with:
      composer-command: |
        composer require yiisoft/yii2:^2.0.52 --prefer-dist --no-progress --no-interaction --no-scripts --ansi
      extensions: intl
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1', '8.2', '8.3']
