---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: ecs

permissions:
  contents: read

jobs:
  easy-coding-standard:
    uses: yii2-framework/actions/.github/workflows/ecs.yml@ea13c0f091d2e888be095dd0265544ff8276dc9f # v2.0.1
