on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

name: ecs

jobs:
  easy-coding-standard:
    uses: php-forge/actions/.github/workflows/ecs.yml@main
    secrets:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    with:
      composer-command: |
        composer require yiisoft/yii2:^2.2.x-dev --prefer-dist --no-progress --no-interaction --no-scripts --ansi
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1']
