---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: ecs

permissions:
  contents: read

jobs:
  easy-coding-standard:
    uses: yii2-framework/actions/.github/workflows/ecs.yml@e02758a41a2a811fb3e706735192979171b2260d # v2.0.1
