---
on:
  - pull_request
  - push

name: quality

permissions:
  contents: read

jobs:
  quality:
    uses: yii2-framework/actions/.github/workflows/quality.yml@ea13c0f091d2e888be095dd0265544ff8276dc9f # v2.0.1
    permissions:
      contents: read
    with:
      codespell-config: .github/linters/.codespellrc
      editorconfig-checker-config: .github/linters/.editorconfig-checker.json
      markdownlint-config: .github/linters/.markdown-lint.yml
      prettier-config: .prettierrc.json
      prettier-ignore-path: .prettierignore
      yamllint-targets: .github
