---
on:
  - pull_request
  - push

name: security

permissions:
  contents: read

jobs:
  security:
    uses: yii2-framework/actions/.github/workflows/security.yml@670b6444a11798dc2b38f2563dbbcef063dfc0ab # v2.0.1
    permissions:
      contents: read
    with:
      gitleaks-config: .github/linters/.gitleaks.toml
    secrets:
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
