---
on:
  pull_request: &ignore-paths
    paths-ignore:
      - ".gitattributes"
      - ".gitignore"
      - "CHANGELOG.md"
      - "docs/**"
      - "README.md"

  push: *ignore-paths

name: static analysis

permissions:
  contents: read
  pull-requests: write

jobs:
  phpstan:
    uses: yii2-framework/actions/.github/workflows/phpstan.yml@v1
    with:
      concurrency-group: phpstan-${{ github.workflow }}-${{ github.ref }}
  phpstan-console:
    uses: yii2-framework/actions/.github/workflows/phpstan.yml@v1
    with:
      configuration: "phpstan-console.neon"
      concurrency-group: |
        phpstan-console-${{ github.workflow }}-${{ github.ref }}
