on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'phpunit.xml.dist'

name: static analysis

jobs:
  phpstan:
    uses: php-forge/actions/.github/workflows/phpstan.yml@v2
    with:
      concurrency-group: phpstan-${{ github.workflow }}-${{ github.ref }}
  phpstan-console:
    uses: php-forge/actions/.github/workflows/phpstan.yml@v2
    with:
      configuration: 'phpstan-console.neon'
      concurrency-group: phpstan-console-${{ github.workflow }}-${{ github.ref }}
